const wordsArray = [
  "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "honeydew",
  "kiwi", "lemon", "mango", "nectarine", "orange", "papaya", "quince", "raspberry",
  "strawberry", "tangerine", "ugli", "vanilla", "watermelon", "xigua", "yam", "zucchini",
  "apricot", "blackberry", "blueberry", "cantaloupe", "dragonfruit", "guava", "jackfruit",
  "kumquat", "lime", "lychee", "mandarin", "mulberry", "olive", "passionfruit", "peach",
  "pear", "pineapple", "plum", "pomegranate", "pumpkin", "starfruit", "tamarind", "tomato",
  "avocado", "broccoli", "cabbage", "carrot", "cauliflower", "celery", "corn", "cucumber",
  "eggplant", "garlic", "ginger", "kale", "lettuce", "mushroom", "onion", "pepper", "potato",
  "radish", "spinach", "squash", "turnip", "yam", "zucchini", "basil", "cilantro", "dill",
  "fennel", "lavender", "mint", "oregano", "parsley", "rosemary", "sage", "thyme", "wasabi",
  "almond", "cashew", "chestnut", "hazelnut", "macadamia", "peanut", "pecan", "pistachio",
  "walnut", "chia", "flax", "hemp", "pumpkin", "sesame", "sunflower"
];

const phrasesArray = [
    "The quick brown fox jumps over the lazy dog every day.",
    "She sells sea shells by the sea shore on sunny days.",
    "He played the violin beautifully at the concert last night.",
    "The children enjoyed the colorful fireworks display at the park.",
    "They traveled to Paris to see the Eiffel Tower and the Louvre.",
    "She baked a delicious chocolate cake for her friend's birthday.",
    "The new restaurant downtown serves the best sushi in the city.",
    "He runs five miles every morning to stay fit and healthy.",
    "The movie was exciting and full of unexpected twists and turns.",
    "The garden is filled with beautiful flowers of every color.",
    "She enjoys reading mystery novels on rainy afternoons.",
    "The old library is a quiet place to study and read books.",
    "He bought a new car and took it for a drive in the countryside.",
    "The family went on a camping trip in the mountains last summer.",
    "The new software update fixed several bugs and improved performance.",
    "She practices yoga every day to maintain her flexibility and balance.",
    "The concert was sold out, and the audience was thrilled by the performance.",
    "The bakery on the corner sells fresh bread and pastries every morning.",
    "The artist painted a beautiful landscape of the sunset over the ocean.",
    "They enjoyed a picnic in the park with sandwiches and lemonade.",
    "The book was so interesting that she couldn't put it down.",
    "The little boy built a sandcastle on the beach with his parents.",
    "The teacher explained the math problem to the students patiently.",
    "They adopted a puppy from the animal shelter and named it Max.",
    "She wore a beautiful red dress to the party last Saturday night.",
    "The city skyline is stunning at night with all the lights shining.",
    "He enjoys hiking in the mountains and exploring nature trails.",
    "The cake was decorated with colorful icing and sprinkles.",
    "The movie theater was packed with people waiting to see the new film.",
    "She learned how to play the piano from her grandmother.",
    "The weather was perfect for a day at the beach with friends.",
    "The cat sat on the windowsill, watching the birds outside.",
    "He loves to cook Italian food, especially pasta dishes.",
    "The museum has an impressive collection of ancient artifacts.",
    "They went on a road trip across the country in their RV.",
    "She enjoys painting landscapes in her free time on weekends.",
    "The new coffee shop in town is a great place to relax.",
    "He read a fascinating book about the history of space exploration.",
    "The garden is full of blooming flowers in the spring.",
    "They watched the sunset together on the beach.",
    "The new exhibit at the museum features modern art.",
    "She loves to write stories about magical adventures.",
    "The park is a great place for a picnic on a sunny day.",
    "He enjoys playing soccer with his friends on weekends.",
    "The concert was amazing, and everyone had a great time.",
    "She makes the best homemade cookies I've ever tasted.",
    "The view from the top of the mountain was breathtaking.",
    "They spent the afternoon exploring the old castle ruins.",
    "The bakery sells the most delicious pastries in town.",
    "He loves to read science fiction novels in his free time.",
    "The sunset over the lake was absolutely stunning.",
    "She enjoys gardening and growing her own vegetables.",
    "The new movie is a must-see for all fans of action films.",
    "They had a great time at the amusement park last weekend.",
    "The festival was filled with music, dancing, and delicious food.",
    "He enjoys fishing at the lake early in the morning.",
    "The bookstore has a great selection of novels and biographies.",
    "She loves to knit scarves and sweaters for her family.",
    "The zoo has many exotic animals from around the world.",
    "They enjoyed a romantic dinner at the new Italian restaurant.",
    "The library is a quiet place to study and read.",
    "He enjoys running in the park every morning.",
    "The new app has many useful features for managing tasks.",
    "She painted a beautiful portrait of her best friend.",
    "The weather was perfect for a hike in the mountains.",
    "They celebrated their anniversary with a special dinner.",
    "The garden is full of colorful flowers in the summer.",
    "He loves to play the guitar and sing songs.",
    "The new restaurant has the best seafood in town.",
    "She enjoys reading books by the fireplace in the winter.",
    "The beach was crowded with people enjoying the sun.",
    "They visited the museum to see the new art exhibit.",
    "The park is a great place for a walk in the evening.",
    "He loves to watch movies with his family on weekends.",
    "The concert was a huge success and everyone had fun.",
    "She makes the most delicious cakes I've ever tasted.",
    "The view from the top of the hill was amazing.",
    "They spent the weekend camping in the forest.",
    "The bakery sells fresh bread and pastries every day.",
    "He loves to read books about history and science.",
    "The sunset over the ocean was beautiful.",
    "She enjoys planting flowers in her garden.",
    "The new movie is a must-see for everyone.",
    "They had a great time at the music festival.",
    "The festival was full of music, dancing, and food.",
    "He enjoys fishing at the river early in the morning.",
    "The bookstore has a great selection of books.",
    "She loves to knit hats and gloves for her friends.",
    "The zoo has many interesting animals to see.",
    "They enjoyed a romantic evening at the restaurant.",
    "The library is a perfect place to study and read.",
    "He enjoys jogging in the park every morning.",
    "The new software has many useful features.",
    "She painted a beautiful landscape of the mountains.",
    "The weather was perfect for a picnic at the park.",
    "They celebrated their wedding anniversary in style.",
    "The garden is full of blooming flowers in spring.",
    "He loves to play the piano and write music.",
    "The new cafe has the best coffee in town.",
    "She enjoys reading mystery novels on rainy days.",
    "The beach was the perfect place to relax.",
    "They visited the art gallery to see the new exhibition.",
    "The park is a wonderful place for a family outing.",
    "He loves to watch football games on Sundays.",
    "The concert was a fantastic experience for everyone.",
    "She makes the best homemade pizzas I've ever had.",
    "The view from the balcony was spectacular.",
    "They spent the holiday exploring the city.",
    "The bakery offers a variety of delicious treats.",
    "He loves to read fantasy novels in his spare time.",
    "The sunset over the mountains was breathtaking.",
    "She enjoys growing her own herbs and vegetables.",
    "The new movie is highly recommended by critics.",
    "They had a wonderful time at the carnival.",
    "The festival was a celebration of culture and tradition.",
    "He enjoys going fishing with his dad on weekends.",
    "The bookstore has a fantastic collection of literature.",
    "She loves to crochet blankets and toys for children.",
    "The zoo is home to many endangered species.",
    "They enjoyed a lovely dinner at the new bistro.",
    "The library is a quiet and peaceful place to study.",
    "He enjoys biking through the park every evening.",
    "The new gadget has many innovative features.",
    "She painted a vibrant picture of the city skyline.",
    "The weather was ideal for a day at the beach.",
    "They celebrated their milestone with a grand party.",
    "The garden is a haven of colorful blooms in summer.",
    "He loves to compose and play his own music.",
    "The new diner has the best burgers in town.",
    "She enjoys reading historical fiction novels.",
    "The beach was a popular spot for tourists.",
    "They visited the science museum to learn new things.",
    "The park is a delightful place for a morning jog.",
    "He loves to watch basketball games with his friends.",
    "The concert was a memorable event for all attendees.",
    "She makes the most delicious homemade pies.",
    "The view from the lighthouse was mesmerizing.",
    "They spent the weekend exploring the countryside.",
    "The bakery is known for its tasty donuts.",
    "He loves to read detective stories and solve puzzles.",
    "The sunset over the lake was picturesque.",
    "She enjoys growing a variety of plants in her garden.",
    "The new thriller movie kept everyone on the edge of their seats.",
    "They had an amazing time at the amusement park.",
    "The festival was an exciting blend of music and art.",
    "He enjoys going fishing at the nearby lake.",
    "The bookstore is a treasure trove of knowledge.",
    "She loves to make handmade jewelry for her friends.",
    "The zoo offers educational programs for children.",
    "They enjoyed a cozy dinner at the new pizzeria.",
    "The library is a perfect place for quiet reflection.",
    "He enjoys taking long walks in the park.",
    "The new smartphone has impressive features.",
    "She painted a serene scene of the countryside.",
    "The weather was perfect for a barbecue in the backyard.",
    "They celebrated the occasion with family and friends.",
    "The garden is a colorful display of summer blooms.",
    "He loves to create and record his own music.",
    "The new bistro has the best desserts in town.",
    "She enjoys reading romantic novels by the fireplace.",
    "The beach was a peaceful retreat from the city.",
    "They visited the aquarium to see the marine life.",
    "The park is a great place for outdoor activities.",
    "He loves to watch baseball games with his son.",
    "The concert was an electrifying experience.",
    "She makes the best homemade lasagna I've ever tasted.",
    "The view from the mountain peak was extraordinary.",
    "They spent the weekend touring the historic sites.",
    "The bakery is famous for its delicious pastries.",
    "He loves to read horror stories late at night.",
    "The sunset over the horizon was captivating.",
    "She enjoys growing a variety of flowers in her garden.",
    "The new documentary movie was informative and engaging.",
    "They had a blast at the music festival.",
    "The festival was a joyful celebration of community.",
    "He enjoys going fishing on his boat every weekend.",
    "The bookstore has a wonderful collection of poetry.",
    "She loves to knit warm scarves for the winter.",
    "The zoo has interactive exhibits for kids.",
    "They enjoyed a delightful dinner at the new cafe.",
    "The library is an ideal place for research and study.",
    "He enjoys running along the beach every morning.",
    "The new app has many useful and fun features.",
    "She painted a colorful mural on the wall.",
    "The weather was perfect for a picnic at the park.",
    "They celebrated the festival with music and dancing.",
    "The garden is a beautiful oasis of color in spring.",
    "He loves to write and perform his own songs.",
    "The new restaurant has the best tacos in town.",
    "She enjoys reading science fiction novels.",
    "The beach was a perfect place for a relaxing day.",
    "They visited the history museum to learn about the past.",
    "The park is a peaceful place for a leisurely walk.",
    "He loves to watch soccer matches with his friends.",
    "The concert was a spectacular performance by the band.",
    "She makes the best homemade apple pie I've ever had.",
    "The view from the cliff was breathtaking.",
    "They spent the holiday exploring the city's landmarks.",
    "The bakery offers a wide range of delicious treats.",
    "He loves to read adventure novels in his spare time.",
    "The sunset over the bay was mesmerizing.",
    "She enjoys growing fresh herbs in her kitchen garden.",
    "The new action movie was a thrilling experience.",
    "They had a wonderful time at the county fair.",
    "The festival was a vibrant display of culture and art.",
    "He enjoys going fishing at the nearby river.",
    "The bookstore is a haven for book lovers.",
    "She loves to create handmade crafts for her friends.",
    "The zoo has many rare and exotic animals.",
    "They enjoyed a lovely dinner at the new diner.",
    "The library is a peaceful place to read and relax.",
    "He enjoys cycling through the park every evening.",
    "The new gadget has many innovative features.",
    "She painted a beautiful picture of the beach.",
    "The weather was ideal for a hike in the mountains.",
    "They celebrated their anniversary with a trip to Paris.",
    "The garden is a colorful display of summer blooms.",
    "He loves to compose and play his own music.",
    "The new cafe has the best lattes in town.",
    "She enjoys reading historical novels.",
    "The beach was a serene escape from the hustle and bustle.",
    "They visited the science museum to explore the exhibits.",
    "The park is a perfect place for a picnic with friends.",
    "He loves to watch basketball games with his family.",
    "The concert was a fantastic experience for everyone.",
    "She makes the best homemade cookies I've ever tasted.",
    "The view from the top of the tower was stunning.",
    "They spent the weekend exploring the countryside.",
    "The bakery is known for its fresh and delicious bread.",
    "He loves to read mystery novels before bed.",
    "The sunset over the mountains was a beautiful sight.",
    "She enjoys growing a variety of plants in her garden.",
    "The new thriller movie was full of suspense and excitement.",
    "They had an amazing time at the amusement park.",
    "The festival was a celebration of music and culture.",
    "He enjoys going fishing at the lake with his friends.",
    "The bookstore has a fantastic selection of books.",
    "She loves to knit warm blankets for the winter.",
    "The zoo offers educational programs for children.",
    "They enjoyed a cozy dinner at the new bistro.",
    "The library is a quiet place to read and study.",
    "He enjoys taking long walks in the park every day.",
    "The new smartphone has many impressive features.",
    "She painted a vibrant landscape of the mountains.",
    "The weather was perfect for a day at the beach.",
    "They celebrated the occasion with a big party.",
    "The garden is full of blooming flowers in spring.",
    "He loves to create and record his own music.",
    "The new diner has the best burgers in town.",
    "She enjoys reading romance novels in her free time.",
    "The beach was the perfect place for a day of fun.",
    "They visited the art museum to see the new exhibit.",
    "The park is a great place for a morning run.",
    "He loves to watch football games with his buddies.",
    "The concert was an incredible experience for all.",
    "She makes the most delicious homemade pizzas.",
    "The view from the mountain was absolutely stunning.",
    "They spent the weekend touring the historic sites.",
    "The bakery sells the best pastries in town.",
    "He loves to read horror stories late at night.",
    "The sunset over the ocean was a breathtaking view.",
    "She enjoys growing a variety of flowers in her garden.",
    "The new documentary movie was fascinating and informative.",
    "They had a blast at the summer music festival.",
    "The festival was a joyful celebration of music and art.",
    "He enjoys going fishing with his father on weekends.",
    "The bookstore is a treasure trove of knowledge.",
    "She loves to crochet blankets and hats for her family.",
    "The zoo has many interesting animals to see.",
    "They enjoyed a romantic dinner at the new restaurant.",
    "The library is a perfect place to study and read.",
    "He enjoys jogging in the park every morning.",
    "The new app has many useful features for users.",
    "She painted a beautiful landscape of the countryside.",
    "The weather was perfect for a picnic in the park.",
    "They celebrated their anniversary with a special dinner.",
    "The garden is full of colorful flowers in summer.",
    "He loves to play the guitar and write songs.",
    "The new coffee shop has the best espresso in town.",
    "She enjoys reading mystery novels on rainy days.",
    "The beach was crowded with people enjoying the sun.",
    "They visited the museum to see the new art exhibit.",
    "The park is a wonderful place for a walk in the evening.",
    "He loves to watch movies with his family on weekends.",
    "The concert was a huge success and everyone had fun.",
    "She makes the most delicious cakes I've ever tasted.",
    "The view from the top of the hill was amazing.",
    "They spent the weekend camping in the forest.",
    "The bakery sells fresh bread and pastries every day.",
    "He loves to read books about history and science.",
    "The sunset over the ocean was beautiful.",
    "She enjoys planting flowers in her garden.",
    "The new movie is a must-see for everyone.",
    "They had a great time at the music festival.",
    "The festival was full of music, dancing, and food.",
    "He enjoys fishing at the river early in the morning.",
    "The bookstore has a great selection of books.",
    "She loves to knit hats and gloves for her friends.",
    "The zoo has many interesting animals to see.",
    "They enjoyed a romantic evening at the restaurant.",
    "The library is a perfect place to study and read.",
    "He enjoys jogging in the park every morning.",
    "The new software has many useful features.",
    "She painted a beautiful landscape of the mountains.",
    "The weather was perfect for a picnic at the park.",
    "They celebrated their wedding anniversary in style.",
    "The garden is full of blooming flowers in spring.",
    "He loves to play the piano and write music.",
    "The new cafe has the best coffee in town.",
    "She enjoys reading mystery novels on rainy days.",
    "The beach was the perfect place to relax.",
    "They visited the art gallery to see the new exhibition.",
    "The park is a delightful place for a family outing.",
    "He loves to watch football games on Sundays.",
    "The concert was a fantastic experience for everyone.",
    "She makes the most delicious homemade cookies.",
    "The view from the balcony was spectacular.",
    "They spent the holiday exploring the city.",
    "The bakery offers a variety of delicious treats.",
    "He loves to read fantasy novels in his spare time.",
    "The sunset over the mountains was breathtaking.",
    "She enjoys growing her own herbs and vegetables.",
    "The new movie is highly recommended by critics.",
    "They had a wonderful time at the carnival.",
    "The festival was a vibrant display of culture and art.",
    "He enjoys going fishing at the nearby lake.",
    "The bookstore is a haven for book lovers.",
    "She loves to make handmade jewelry for her friends.",
    "The zoo offers educational programs for children.",
    "They enjoyed a cozy dinner at the new bistro.",
    "The library is an ideal place for research and study.",
    "He enjoys biking through the park every evening.",
    "The new gadget has many innovative features.",
    "She painted a serene scene of the countryside.",
    "The weather was perfect for a barbecue in the backyard.",
    "They celebrated the occasion with family and friends.",
    "The garden is a colorful display of summer blooms.",
    "He loves to create and record his own music.",
    "The new diner has the best burgers in town.",
    "She enjoys reading romantic novels by the fireplace.",
    "The beach was a peaceful retreat from the city.",
    "They visited the aquarium to see the marine life.",
    "The park is a great place for outdoor activities.",
    "He loves to watch baseball games with his son.",
    "The concert was an electrifying experience.",
    "She makes the best homemade lasagna I've ever tasted.",
    "The view from the cliff was breathtaking.",
    "They spent the weekend exploring the countryside.",
    "The bakery is known for its tasty donuts.",
    "He loves to read detective stories and solve puzzles.",
    "The sunset over the lake was picturesque.",
    "She enjoys growing a variety of plants in her garden.",
    "The new thriller movie kept everyone on the edge of their seats.",
    "They had an amazing time at the amusement park.",
    "The festival was an exciting blend of music and art.",
    "He enjoys going fishing at the nearby lake.",
    "The bookstore is a treasure trove of knowledge.",
    "She loves to knit warm scarves for the winter.",
    "The zoo offers interactive exhibits for kids.",
    "They enjoyed a delightful dinner at the new cafe.",
    "The library is a peaceful place to read and relax.",
    "He enjoys running along the beach every morning.",
    "The new gadget has many innovative features.",
    "She painted a beautiful picture of the beach.",
    "The weather was ideal for a hike in the mountains.",
    "They celebrated their anniversary with a trip to Paris.",
    "The garden is a colorful display of summer blooms.",
    "He loves to compose and play his own music.",
    "The new cafe has the best lattes in town.",
    "She enjoys reading historical novels.",
    "The beach was a serene escape from the hustle and bustle.",
    "They visited the science museum to explore the exhibits.",
    "The park is a perfect place for a picnic with friends.",
    "He loves to watch basketball games with his family.",
    "The concert was a fantastic experience for everyone.",
    "She makes the best homemade cookies I've ever tasted.",
    "The view from the top of the tower was stunning.",
    "They spent the weekend exploring the countryside.",
    "The bakery is known for its fresh and delicious bread.",
    "He loves to read mystery novels before bed.",
    "The sunset over the mountains was a beautiful sight.",
    "She enjoys growing a variety of plants in her garden.",
    "The new thriller movie was full of suspense and excitement.",
    "They had an amazing time at the amusement park.",
    "The festival was a celebration of music and culture.",
    "He enjoys going fishing at the lake with his friends.",
    "The bookstore has a fantastic selection of books.",
    "She loves to knit warm blankets for the winter.",
    "The zoo offers educational programs for children.",
    "They enjoyed a cozy dinner at the new bistro.",
    "The library is a quiet place to read and study.",
    "He enjoys taking long walks in the park every day.",
    "The new smartphone has many impressive features.",
    "She painted a vibrant landscape of the mountains.",
    "The weather was perfect for a day at the beach.",
    "They celebrated the occasion with a big party.",
    "The garden is full of blooming flowers in spring.",
    "He loves to create and record his own music.",
    "The new diner has the best burgers in town.",
    "She enjoys reading romance novels in her free time.",
    "The beach was the perfect place for a day of fun.",
    "They visited the art museum to see the new exhibit.",
    "The park is a great place for a morning run.",
    "He loves to watch football games with his buddies.",
    "The concert was an incredible experience for all."
  ];